language: node_js
node_js:
  - "stable"

cache:
  directories:
    - node_modules

script:
  - npm run build
  
  # TODO: this should be run only on tags: true
  - cd  build
  - zip - r notebook-classroom.zip ./*
  - cd ..
  - mv build/notebook-classroom.zip ./notebook-classroom.zip
  
  - ls

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: ./build
    on:
      branch: master
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    #file_glob: true
    #file: build/*
    file: notebook-classroom.zip
    on:
      tags: true
