language: node_js
node_js:
  - "stable"

cache:
  directories:
    - node_modules

script:
  - npm run build
  - ls

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: ./build
    on:
      branch: master
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: build/*
    on:
      tags: true
